# Generated by Django 4.2.7 on 2023-12-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegpricetrend',
            name='veg_month',
        ),
        migrations.RemoveField(
            model_name='vegpricetrend',
            name='veg_year',
        ),
    ]
