# Generated by Django 4.2.7 on 2023-12-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg_app', '0002_remove_vegpricetrend_veg_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegpricetrend',
            name='veg_name',
            field=models.CharField(choices=[('キャベツ', 'キャベツ'), ('レタス', 'レタス'), ('かぶ', 'かぶ'), ('きゅうり', 'きゅうり'), ('小松菜', '小松菜'), ('ごぼう', 'ごぼう'), ('さつまいも', 'さつまいも'), ('島唐辛子', '島唐辛子'), ('春菊', '春菊'), ('玉ねぎ', '玉ねぎ'), ('大根', '大根'), ('ちんげんさい', 'ちんげんさい'), ('なす', 'なす'), ('にら', 'にら'), ('人参', '人参'), ('ねぎ', 'ねぎ'), ('白菜', '白菜'), ('じゃがいも', 'じゃがいも'), ('ほうれん草', 'ほうれん草'), ('水菜', '水菜'), ('山芋', '山芋'), ('レンコン', 'レンコン'), ('カリフラワー', 'カリフラワー'), ('セロリ', 'セロリ'), ('トマト', 'トマト'), ('ピーマン', 'ピーマン')], max_length=255, null=True, verbose_name='野菜の種類'),
        ),
    ]
