# Generated by Django 4.2.7 on 2024-02-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg_app', '0003_alter_vegpricetrend_veg_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='月')),
                ('vegetable_name', models.CharField(choices=[('キャベツ', 'キャベツ'), ('レタス', 'レタス'), ('かぶ', 'かぶ'), ('きゅうり', 'きゅうり'), ('小松菜', '小松菜'), ('ごぼう', 'ごぼう'), ('さつまいも', 'さつまいも'), ('島唐辛子', '島唐辛子'), ('春菊', '春菊'), ('玉ねぎ', '玉ねぎ'), ('大根', '大根'), ('ちんげんさい', 'ちんげんさい'), ('なす', 'なす'), ('にら', 'にら'), ('人参', '人参'), ('ねぎ', 'ねぎ'), ('白菜', '白菜'), ('じゃがいも', 'じゃがいも'), ('ほうれん草', 'ほうれん草'), ('水菜', '水菜'), ('山芋', '山芋'), ('レンコン', 'レンコン'), ('カリフラワー', 'カリフラワー'), ('セロリ', 'セロリ'), ('トマト', 'トマト'), ('ピーマン', 'ピーマン')], max_length=255, verbose_name='野菜名')),
                ('pref_name', models.CharField(choices=[('gunma', '群馬'), ('chibca', '千葉'), ('ibaraki', '茨城'), ('iwate', '岩手'), ('kanagawa', '神奈川'), ('nagano', '長野'), ('hyogo', '兵庫'), ('tochigi', '栃木'), ('fukuoka', '福岡'), ('yamanashi', '山梨'), ('nagasaki', '長崎'), ('shizuoka', '静岡'), ('kagawa', '香川'), ('kumamoto', '熊本'), ('hokkaido', '北海道'), ('saitama', '埼玉'), ('kochi', '高知'), ('kagoshima', '鹿児島'), ('tokushima', '徳島'), ('okinawa', '沖縄'), ('akita', '秋田'), ('nigata', '新潟'), ('yamagata', '山形'), ('aomori', '青森'), ('miyazaki', '宮崎'), ('tokyo', '東京'), ('miyazaki', '宮崎'), ('tokushima', '徳島'), ('saga', '佐賀'), ('kumamoto', '熊本'), ('gifu', '岐阜'), ('oasaka', '大阪')], max_length=255, verbose_name='都道府県名')),
                ('amount', models.FloatField(null=True, verbose_name='出荷量')),
            ],
        ),
        migrations.CreateModel(
            name='VegetablePriceByPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(null=True, verbose_name='日付')),
                ('pref_name', models.CharField(choices=[('gunma', '群馬'), ('chibca', '千葉'), ('ibaraki', '茨城'), ('iwate', '岩手'), ('kanagawa', '神奈川'), ('nagano', '長野'), ('hyogo', '兵庫'), ('tochigi', '栃木'), ('fukuoka', '福岡'), ('yamanashi', '山梨'), ('nagasaki', '長崎'), ('shizuoka', '静岡'), ('kagawa', '香川'), ('kumamoto', '熊本'), ('hokkaido', '北海道'), ('saitama', '埼玉'), ('kochi', '高知'), ('kagoshima', '鹿児島'), ('tokushima', '徳島'), ('okinawa', '沖縄'), ('akita', '秋田'), ('nigata', '新潟'), ('yamagata', '山形'), ('aomori', '青森'), ('miyazaki', '宮崎'), ('tokyo', '東京'), ('miyazaki', '宮崎'), ('tokushima', '徳島'), ('saga', '佐賀'), ('kumamoto', '熊本'), ('gifu', '岐阜'), ('oasaka', '大阪')], max_length=255, verbose_name='都道府県名')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='価格')),
                ('vegetable_name', models.CharField(choices=[('キャベツ', 'キャベツ'), ('レタス', 'レタス'), ('かぶ', 'かぶ'), ('きゅうり', 'きゅうり'), ('小松菜', '小松菜'), ('ごぼう', 'ごぼう'), ('さつまいも', 'さつまいも'), ('島唐辛子', '島唐辛子'), ('春菊', '春菊'), ('玉ねぎ', '玉ねぎ'), ('大根', '大根'), ('ちんげんさい', 'ちんげんさい'), ('なす', 'なす'), ('にら', 'にら'), ('人参', '人参'), ('ねぎ', 'ねぎ'), ('白菜', '白菜'), ('じゃがいも', 'じゃがいも'), ('ほうれん草', 'ほうれん草'), ('水菜', '水菜'), ('山芋', '山芋'), ('レンコン', 'レンコン'), ('カリフラワー', 'カリフラワー'), ('セロリ', 'セロリ'), ('トマト', 'トマト'), ('ピーマン', 'ピーマン')], max_length=255, verbose_name='野菜名')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(null=True, verbose_name='日付')),
                ('pref_name', models.CharField(choices=[('gunma', '群馬'), ('chibca', '千葉'), ('ibaraki', '茨城'), ('iwate', '岩手'), ('kanagawa', '神奈川'), ('nagano', '長野'), ('hyogo', '兵庫'), ('tochigi', '栃木'), ('fukuoka', '福岡'), ('yamanashi', '山梨'), ('nagasaki', '長崎'), ('shizuoka', '静岡'), ('kagawa', '香川'), ('kumamoto', '熊本'), ('hokkaido', '北海道'), ('saitama', '埼玉'), ('kochi', '高知'), ('kagoshima', '鹿児島'), ('tokushima', '徳島'), ('okinawa', '沖縄'), ('akita', '秋田'), ('nigata', '新潟'), ('yamagata', '山形'), ('aomori', '青森'), ('miyazaki', '宮崎'), ('tokyo', '東京'), ('miyazaki', '宮崎'), ('tokushima', '徳島'), ('saga', '佐賀'), ('kumamoto', '熊本'), ('gifu', '岐阜'), ('oasaka', '大阪')], max_length=255, verbose_name='都道府県名')),
                ('amount', models.FloatField(null=True, verbose_name='観測量')),
                ('item', models.CharField(choices=[('total_rain_average', '平均降雨量'), ('mean_temp_average', '平均気温'), ('max_temp_average', '最高気温の平均'), ('min_temp_average', '最低気温の平均'), ('mean_humidity_average', '湿度の平均'), ('max_wind_average', '最大風速の平均'), ('max_instantaneous_wind_average', '最大瞬間風速の平均'), ('sunshine_hour_average', '日照時間の平均'), ('total_snow_average', '平均降雪量'), ('snow_deepest_average', '平均積雪量'), ('temp_more_30_days', '30度以上を記録した日数'), ('temp_more_35_days', '35度以上を記録した日数'), ('temp_less_10_days', '10度以下を記録した日数'), ('temp_less_0_days', '0度以下を記録した日数'), ('rain_days', '降雨日数'), ('snow_days', '降雪日数'), ('typhoon_days', '台風が来た数'), ('total_rain_for_3month', '降雨量の合計'), ('total_sunshine_for_3month', '日照時間の合計'), ('total_snow_for_3month', '降雪量の合計')], max_length=255, verbose_name='観測項目')),
            ],
        ),
    ]
